import GromovFilling.Constants
import GromovFilling.FourierBoundary
import GromovFilling.FourierBessel
import GromovFilling.Universal
import GromovFilling.JacobianBudget
import GromovFilling.ComplexJacobianBudget
import GromovFilling.Givens
import GromovFilling.DominantHarmonic
import GromovFilling.DominantHarmonicDisk
import GromovFilling.PolynomialDiskArea
import GromovFilling.GivensDisk
import GromovFilling.GivensDiskArea
import GromovFilling.PlanarCertificate
import GromovFilling.DistanceProfile
import GromovFilling.ProfileFourier
import GromovFilling.MetricPlanarCoverage
import GromovFilling.BoundaryCertificate
import GromovFilling.FourierArea
import GromovFilling.ModTwoDegree
import GromovFilling.RadialProjection
import GromovFilling.CircleDegree
import GromovFilling.BoundarySubdivisionDegree
import GromovFilling.PolygonalSurfaceObstruction
import GromovFilling.FinePolygonalModel
import GromovFilling.GeneralSurfaceObstruction
import GromovFilling.SurfaceCoverage
import GromovFilling.EuclideanAreaFormula
import GromovFilling.ComplexAreaFormula
import GromovFilling.DominantHarmonicDegree
import GromovFilling.BoundaryDegree
import GromovFilling.RadialDegreeStability
import GromovFilling.BoundaryDegreeComponents
import GromovFilling.JordanBoundary
import GromovFilling.ClosedOneForm
import GromovFilling.Oriented
import GromovFilling.BoundaryActionSeries
import GromovFilling.Numerics
import GromovFilling.Certificates
import GromovFilling.GeometricCertificates
import GromovFilling.GeometricClosedOneForm

/-!
# Fourier certificates for Gromov's filling-area problem

This file formalizes the exact real-analysis and certificate arguments used by
the two headline bounds in `fourier_resonant_filling_area_v3.tex`.
-/

namespace GromovFilling

end GromovFilling
